export declare enum AlertInformationType {
    AUTHORIZATION_TRANSACTION = 0,
    CONFIRM_DELETE_DATA = 1,
    DELETE_DATA = 2,
    INFORMATION_NOT_VALID = 3,
    LOST_DATA = 4,
    UNCOMPLETED_DATA = 5,
    UNCOMPLETED_SELECTED_DATA = 6,
    DEFINE_COMMERCIAL_STRUCTURE = 7,
    DEFINE_PARKING_STRUCTURE = 8,
    DEFINE_RESIDENCIAL_STRUCTURE = 9
}
